//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaGUI.ServiceCliente {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceCliente.WebServiceClienteSoap")]
    public interface WebServiceClienteSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SListaCliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable SListaCliente(string filtro, bool sentido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SListaCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> SListaClienteAsync(string filtro, bool sentido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SRegistrarCliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool SRegistrarCliente(CapaGUI.ServiceCliente.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SRegistrarCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> SRegistrarClienteAsync(CapaGUI.ServiceCliente.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SBuscaClienteString", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable SBuscaClienteString(string filtro, string valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SBuscaClienteString", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> SBuscaClienteStringAsync(string filtro, string valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SBuscaClienteInt", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable SBuscaClienteInt(string filtro, int valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SBuscaClienteInt", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> SBuscaClienteIntAsync(string filtro, int valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SActualizaCliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool SActualizaCliente(CapaGUI.ServiceCliente.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SActualizaCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> SActualizaClienteAsync(CapaGUI.ServiceCliente.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SEliminaCliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool SEliminaCliente(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SEliminaCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> SEliminaClienteAsync(int id);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Cliente : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int tbUsuario_IdUsuarioField;
        
        private string nombreCompletoField;
        
        private int edadField;
        
        private int telefonoField;
        
        private string emailField;
        
        private string sexoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int TbUsuario_IdUsuario {
            get {
                return this.tbUsuario_IdUsuarioField;
            }
            set {
                this.tbUsuario_IdUsuarioField = value;
                this.RaisePropertyChanged("TbUsuario_IdUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string NombreCompleto {
            get {
                return this.nombreCompletoField;
            }
            set {
                this.nombreCompletoField = value;
                this.RaisePropertyChanged("NombreCompleto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Edad {
            get {
                return this.edadField;
            }
            set {
                this.edadField = value;
                this.RaisePropertyChanged("Edad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("Telefono");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
                this.RaisePropertyChanged("Sexo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceClienteSoapChannel : CapaGUI.ServiceCliente.WebServiceClienteSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceClienteSoapClient : System.ServiceModel.ClientBase<CapaGUI.ServiceCliente.WebServiceClienteSoap>, CapaGUI.ServiceCliente.WebServiceClienteSoap {
        
        public WebServiceClienteSoapClient() {
        }
        
        public WebServiceClienteSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceClienteSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceClienteSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceClienteSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable SListaCliente(string filtro, bool sentido) {
            return base.Channel.SListaCliente(filtro, sentido);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> SListaClienteAsync(string filtro, bool sentido) {
            return base.Channel.SListaClienteAsync(filtro, sentido);
        }
        
        public bool SRegistrarCliente(CapaGUI.ServiceCliente.Cliente cliente) {
            return base.Channel.SRegistrarCliente(cliente);
        }
        
        public System.Threading.Tasks.Task<bool> SRegistrarClienteAsync(CapaGUI.ServiceCliente.Cliente cliente) {
            return base.Channel.SRegistrarClienteAsync(cliente);
        }
        
        public System.Data.DataTable SBuscaClienteString(string filtro, string valor) {
            return base.Channel.SBuscaClienteString(filtro, valor);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> SBuscaClienteStringAsync(string filtro, string valor) {
            return base.Channel.SBuscaClienteStringAsync(filtro, valor);
        }
        
        public System.Data.DataTable SBuscaClienteInt(string filtro, int valor) {
            return base.Channel.SBuscaClienteInt(filtro, valor);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> SBuscaClienteIntAsync(string filtro, int valor) {
            return base.Channel.SBuscaClienteIntAsync(filtro, valor);
        }
        
        public bool SActualizaCliente(CapaGUI.ServiceCliente.Cliente cliente) {
            return base.Channel.SActualizaCliente(cliente);
        }
        
        public System.Threading.Tasks.Task<bool> SActualizaClienteAsync(CapaGUI.ServiceCliente.Cliente cliente) {
            return base.Channel.SActualizaClienteAsync(cliente);
        }
        
        public bool SEliminaCliente(int id) {
            return base.Channel.SEliminaCliente(id);
        }
        
        public System.Threading.Tasks.Task<bool> SEliminaClienteAsync(int id) {
            return base.Channel.SEliminaClienteAsync(id);
        }
    }
}
