//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaGUI.ServiceUsuario {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceUsuario.WebServiceUsuarioSoap")]
    public interface WebServiceUsuarioSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SRegistrarUsuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int SRegistrarUsuario(string nombre, string contra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SRegistrarUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<int> SRegistrarUsuarioAsync(string nombre, string contra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SListarUsuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable SListarUsuario(string filtro, bool sentido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SListarUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> SListarUsuarioAsync(string filtro, bool sentido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SBuscaUsuarioObj", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaGUI.ServiceUsuario.Usuario SBuscaUsuarioObj(string filtro, string valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SBuscaUsuarioObj", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaGUI.ServiceUsuario.Usuario> SBuscaUsuarioObjAsync(string filtro, string valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SBuscaUsuarioString", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SBuscaUsuarioString(string filtro, string valor, bool esId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SBuscaUsuarioString", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SBuscaUsuarioStringAsync(string filtro, string valor, bool esId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SActualizaUsuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool SActualizaUsuario(CapaGUI.ServiceUsuario.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SActualizaUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> SActualizaUsuarioAsync(CapaGUI.ServiceUsuario.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SEliminaUsuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool SEliminaUsuario(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SEliminaUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> SEliminaUsuarioAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SCreaCliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool SCreaCliente(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SCreaCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> SCreaClienteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SUltimoUsuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int SUltimoUsuario();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SUltimoUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<int> SUltimoUsuarioAsync();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Usuario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idUsuarioField;
        
        private string nombreUsuarioField;
        
        private string contrasenaField;
        
        private string rolField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int IdUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
                this.RaisePropertyChanged("IdUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string NombreUsuario {
            get {
                return this.nombreUsuarioField;
            }
            set {
                this.nombreUsuarioField = value;
                this.RaisePropertyChanged("NombreUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Contrasena {
            get {
                return this.contrasenaField;
            }
            set {
                this.contrasenaField = value;
                this.RaisePropertyChanged("Contrasena");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Rol {
            get {
                return this.rolField;
            }
            set {
                this.rolField = value;
                this.RaisePropertyChanged("Rol");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceUsuarioSoapChannel : CapaGUI.ServiceUsuario.WebServiceUsuarioSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceUsuarioSoapClient : System.ServiceModel.ClientBase<CapaGUI.ServiceUsuario.WebServiceUsuarioSoap>, CapaGUI.ServiceUsuario.WebServiceUsuarioSoap {
        
        public WebServiceUsuarioSoapClient() {
        }
        
        public WebServiceUsuarioSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceUsuarioSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceUsuarioSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceUsuarioSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int SRegistrarUsuario(string nombre, string contra) {
            return base.Channel.SRegistrarUsuario(nombre, contra);
        }
        
        public System.Threading.Tasks.Task<int> SRegistrarUsuarioAsync(string nombre, string contra) {
            return base.Channel.SRegistrarUsuarioAsync(nombre, contra);
        }
        
        public System.Data.DataTable SListarUsuario(string filtro, bool sentido) {
            return base.Channel.SListarUsuario(filtro, sentido);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> SListarUsuarioAsync(string filtro, bool sentido) {
            return base.Channel.SListarUsuarioAsync(filtro, sentido);
        }
        
        public CapaGUI.ServiceUsuario.Usuario SBuscaUsuarioObj(string filtro, string valor) {
            return base.Channel.SBuscaUsuarioObj(filtro, valor);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServiceUsuario.Usuario> SBuscaUsuarioObjAsync(string filtro, string valor) {
            return base.Channel.SBuscaUsuarioObjAsync(filtro, valor);
        }
        
        public string SBuscaUsuarioString(string filtro, string valor, bool esId) {
            return base.Channel.SBuscaUsuarioString(filtro, valor, esId);
        }
        
        public System.Threading.Tasks.Task<string> SBuscaUsuarioStringAsync(string filtro, string valor, bool esId) {
            return base.Channel.SBuscaUsuarioStringAsync(filtro, valor, esId);
        }
        
        public bool SActualizaUsuario(CapaGUI.ServiceUsuario.Usuario usuario) {
            return base.Channel.SActualizaUsuario(usuario);
        }
        
        public System.Threading.Tasks.Task<bool> SActualizaUsuarioAsync(CapaGUI.ServiceUsuario.Usuario usuario) {
            return base.Channel.SActualizaUsuarioAsync(usuario);
        }
        
        public bool SEliminaUsuario(int id) {
            return base.Channel.SEliminaUsuario(id);
        }
        
        public System.Threading.Tasks.Task<bool> SEliminaUsuarioAsync(int id) {
            return base.Channel.SEliminaUsuarioAsync(id);
        }
        
        public bool SCreaCliente(int id) {
            return base.Channel.SCreaCliente(id);
        }
        
        public System.Threading.Tasks.Task<bool> SCreaClienteAsync(int id) {
            return base.Channel.SCreaClienteAsync(id);
        }
        
        public int SUltimoUsuario() {
            return base.Channel.SUltimoUsuario();
        }
        
        public System.Threading.Tasks.Task<int> SUltimoUsuarioAsync() {
            return base.Channel.SUltimoUsuarioAsync();
        }
    }
}
