//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaGUI.ServiceEmpleado {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceEmpleado.WebServiceEmpleadoSoap")]
    public interface WebServiceEmpleadoSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SListaEmpleado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable SListaEmpleado(string filtro, bool sentido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SListaEmpleado", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> SListaEmpleadoAsync(string filtro, bool sentido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SRegistrarEmpleado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool SRegistrarEmpleado(CapaGUI.ServiceEmpleado.Empleado empleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SRegistrarEmpleado", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> SRegistrarEmpleadoAsync(CapaGUI.ServiceEmpleado.Empleado empleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SBuscaEmpleado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable SBuscaEmpleado(string filtro, string valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SBuscaEmpleado", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> SBuscaEmpleadoAsync(string filtro, string valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SActualizaEmpleado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool SActualizaEmpleado(CapaGUI.ServiceEmpleado.Empleado empleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SActualizaEmpleado", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> SActualizaEmpleadoAsync(CapaGUI.ServiceEmpleado.Empleado empleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SEliminaEmpleado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool SEliminaEmpleado(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SEliminaEmpleado", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> SEliminaEmpleadoAsync(int id);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Empleado : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nombreCompletoField;
        
        private int edadField;
        
        private int telefonoField;
        
        private string emailField;
        
        private string sexoField;
        
        private int tbUsuario_IdUsuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string NombreCompleto {
            get {
                return this.nombreCompletoField;
            }
            set {
                this.nombreCompletoField = value;
                this.RaisePropertyChanged("NombreCompleto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Edad {
            get {
                return this.edadField;
            }
            set {
                this.edadField = value;
                this.RaisePropertyChanged("Edad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("Telefono");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
                this.RaisePropertyChanged("Sexo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int TbUsuario_IdUsuario {
            get {
                return this.tbUsuario_IdUsuarioField;
            }
            set {
                this.tbUsuario_IdUsuarioField = value;
                this.RaisePropertyChanged("TbUsuario_IdUsuario");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceEmpleadoSoapChannel : CapaGUI.ServiceEmpleado.WebServiceEmpleadoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceEmpleadoSoapClient : System.ServiceModel.ClientBase<CapaGUI.ServiceEmpleado.WebServiceEmpleadoSoap>, CapaGUI.ServiceEmpleado.WebServiceEmpleadoSoap {
        
        public WebServiceEmpleadoSoapClient() {
        }
        
        public WebServiceEmpleadoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceEmpleadoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceEmpleadoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceEmpleadoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable SListaEmpleado(string filtro, bool sentido) {
            return base.Channel.SListaEmpleado(filtro, sentido);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> SListaEmpleadoAsync(string filtro, bool sentido) {
            return base.Channel.SListaEmpleadoAsync(filtro, sentido);
        }
        
        public bool SRegistrarEmpleado(CapaGUI.ServiceEmpleado.Empleado empleado) {
            return base.Channel.SRegistrarEmpleado(empleado);
        }
        
        public System.Threading.Tasks.Task<bool> SRegistrarEmpleadoAsync(CapaGUI.ServiceEmpleado.Empleado empleado) {
            return base.Channel.SRegistrarEmpleadoAsync(empleado);
        }
        
        public System.Data.DataTable SBuscaEmpleado(string filtro, string valor) {
            return base.Channel.SBuscaEmpleado(filtro, valor);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> SBuscaEmpleadoAsync(string filtro, string valor) {
            return base.Channel.SBuscaEmpleadoAsync(filtro, valor);
        }
        
        public bool SActualizaEmpleado(CapaGUI.ServiceEmpleado.Empleado empleado) {
            return base.Channel.SActualizaEmpleado(empleado);
        }
        
        public System.Threading.Tasks.Task<bool> SActualizaEmpleadoAsync(CapaGUI.ServiceEmpleado.Empleado empleado) {
            return base.Channel.SActualizaEmpleadoAsync(empleado);
        }
        
        public bool SEliminaEmpleado(int id) {
            return base.Channel.SEliminaEmpleado(id);
        }
        
        public System.Threading.Tasks.Task<bool> SEliminaEmpleadoAsync(int id) {
            return base.Channel.SEliminaEmpleadoAsync(id);
        }
    }
}
