//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaGUI.ServiceEmpleado {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceEmpleado.WebServiceUsuarioEmpleadoSoap")]
    public interface WebServiceUsuarioEmpleadoSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceRegistrarProducto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ServiceRegistrarProducto(CapaGUI.ServiceEmpleado.Producto producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceRegistrarProducto", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ServiceRegistrarProductoAsync(CapaGUI.ServiceEmpleado.Producto producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceActualizaProducto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ServiceActualizaProducto(CapaGUI.ServiceEmpleado.Producto producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceActualizaProducto", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ServiceActualizaProductoAsync(CapaGUI.ServiceEmpleado.Producto producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceListaProducto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ServiceListaProducto(string filtro, bool sentido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceListaProducto", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ServiceListaProductoAsync(string filtro, bool sentido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceBuscaProducto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ServiceBuscaProducto(string filtro, string valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceBuscaProducto", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ServiceBuscaProductoAsync(string filtro, string valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceEliminaProducto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ServiceEliminaProducto(string sku);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceEliminaProducto", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ServiceEliminaProductoAsync(string sku);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceListaCliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ServiceListaCliente(string filtro, bool sentido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceListaCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ServiceListaClienteAsync(string filtro, bool sentido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceBuscaClienteS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ServiceBuscaClienteS(string filtro, string valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceBuscaClienteS", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ServiceBuscaClienteSAsync(string filtro, string valor);
        
        // CODEGEN: Generating message contract since the wrapper name (Busca_clientes_utilizando_un_parametro_int) of message Busca_clientes_utilizando_un_parametro_int does not match the default value (ServiceBuscaClienteN)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Busca_clientes_utilizando_un_parametro_int", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaGUI.ServiceEmpleado.Busca_clientes_utilizando_un_parametro_int1 ServiceBuscaClienteN(CapaGUI.ServiceEmpleado.Busca_clientes_utilizando_un_parametro_int request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Busca_clientes_utilizando_un_parametro_int", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaGUI.ServiceEmpleado.Busca_clientes_utilizando_un_parametro_int1> ServiceBuscaClienteNAsync(CapaGUI.ServiceEmpleado.Busca_clientes_utilizando_un_parametro_int request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceActualizaCliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ServiceActualizaCliente(CapaGUI.ServiceEmpleado.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceActualizaCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ServiceActualizaClienteAsync(CapaGUI.ServiceEmpleado.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceEliminaCliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ServiceEliminaCliente(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceEliminaCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ServiceEliminaClienteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceActualizaUsuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ServiceActualizaUsuario(CapaGUI.ServiceEmpleado.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceActualizaUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ServiceActualizaUsuarioAsync(CapaGUI.ServiceEmpleado.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceRegistraCliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ServiceRegistraCliente(CapaGUI.ServiceEmpleado.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceRegistraCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ServiceRegistraClienteAsync(CapaGUI.ServiceEmpleado.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceBuscaEmpleado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ServiceBuscaEmpleado(string filtro, string valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceBuscaEmpleado", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ServiceBuscaEmpleadoAsync(string filtro, string valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceActualizaEmpleado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ServiceActualizaEmpleado(CapaGUI.ServiceEmpleado.Empleado empleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceActualizaEmpleado", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ServiceActualizaEmpleadoAsync(CapaGUI.ServiceEmpleado.Empleado empleado);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Producto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string skuField;
        
        private string nombreProductoField;
        
        private int valorField;
        
        private double cantPaqueteField;
        
        private string unidadMedidaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Sku {
            get {
                return this.skuField;
            }
            set {
                this.skuField = value;
                this.RaisePropertyChanged("Sku");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string NombreProducto {
            get {
                return this.nombreProductoField;
            }
            set {
                this.nombreProductoField = value;
                this.RaisePropertyChanged("NombreProducto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
                this.RaisePropertyChanged("Valor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public double CantPaquete {
            get {
                return this.cantPaqueteField;
            }
            set {
                this.cantPaqueteField = value;
                this.RaisePropertyChanged("CantPaquete");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string UnidadMedida {
            get {
                return this.unidadMedidaField;
            }
            set {
                this.unidadMedidaField = value;
                this.RaisePropertyChanged("UnidadMedida");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Empleado : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nombreCompletoField;
        
        private int edadField;
        
        private int telefonoField;
        
        private string emailField;
        
        private string sexoField;
        
        private int tbUsuario_IdUsuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string NombreCompleto {
            get {
                return this.nombreCompletoField;
            }
            set {
                this.nombreCompletoField = value;
                this.RaisePropertyChanged("NombreCompleto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Edad {
            get {
                return this.edadField;
            }
            set {
                this.edadField = value;
                this.RaisePropertyChanged("Edad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("Telefono");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
                this.RaisePropertyChanged("Sexo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int TbUsuario_IdUsuario {
            get {
                return this.tbUsuario_IdUsuarioField;
            }
            set {
                this.tbUsuario_IdUsuarioField = value;
                this.RaisePropertyChanged("TbUsuario_IdUsuario");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Usuario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idUsuarioField;
        
        private string nombreUsuarioField;
        
        private string contrasenaField;
        
        private string rolField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int IdUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
                this.RaisePropertyChanged("IdUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string NombreUsuario {
            get {
                return this.nombreUsuarioField;
            }
            set {
                this.nombreUsuarioField = value;
                this.RaisePropertyChanged("NombreUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Contrasena {
            get {
                return this.contrasenaField;
            }
            set {
                this.contrasenaField = value;
                this.RaisePropertyChanged("Contrasena");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Rol {
            get {
                return this.rolField;
            }
            set {
                this.rolField = value;
                this.RaisePropertyChanged("Rol");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Cliente : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int tbUsuario_IdUsuarioField;
        
        private string nombreCompletoField;
        
        private int edadField;
        
        private int telefonoField;
        
        private string emailField;
        
        private string sexoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int TbUsuario_IdUsuario {
            get {
                return this.tbUsuario_IdUsuarioField;
            }
            set {
                this.tbUsuario_IdUsuarioField = value;
                this.RaisePropertyChanged("TbUsuario_IdUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string NombreCompleto {
            get {
                return this.nombreCompletoField;
            }
            set {
                this.nombreCompletoField = value;
                this.RaisePropertyChanged("NombreCompleto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Edad {
            get {
                return this.edadField;
            }
            set {
                this.edadField = value;
                this.RaisePropertyChanged("Edad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("Telefono");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
                this.RaisePropertyChanged("Sexo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Busca_clientes_utilizando_un_parametro_int", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Busca_clientes_utilizando_un_parametro_int {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string filtro;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int valor;
        
        public Busca_clientes_utilizando_un_parametro_int() {
        }
        
        public Busca_clientes_utilizando_un_parametro_int(string filtro, int valor) {
            this.filtro = filtro;
            this.valor = valor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Busca_clientes_utilizando_un_parametro_intResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Busca_clientes_utilizando_un_parametro_int1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataTable Busca_clientes_utilizando_un_parametro_intResult;
        
        public Busca_clientes_utilizando_un_parametro_int1() {
        }
        
        public Busca_clientes_utilizando_un_parametro_int1(System.Data.DataTable Busca_clientes_utilizando_un_parametro_intResult) {
            this.Busca_clientes_utilizando_un_parametro_intResult = Busca_clientes_utilizando_un_parametro_intResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceUsuarioEmpleadoSoapChannel : CapaGUI.ServiceEmpleado.WebServiceUsuarioEmpleadoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceUsuarioEmpleadoSoapClient : System.ServiceModel.ClientBase<CapaGUI.ServiceEmpleado.WebServiceUsuarioEmpleadoSoap>, CapaGUI.ServiceEmpleado.WebServiceUsuarioEmpleadoSoap {
        
        public WebServiceUsuarioEmpleadoSoapClient() {
        }
        
        public WebServiceUsuarioEmpleadoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceUsuarioEmpleadoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceUsuarioEmpleadoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceUsuarioEmpleadoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool ServiceRegistrarProducto(CapaGUI.ServiceEmpleado.Producto producto) {
            return base.Channel.ServiceRegistrarProducto(producto);
        }
        
        public System.Threading.Tasks.Task<bool> ServiceRegistrarProductoAsync(CapaGUI.ServiceEmpleado.Producto producto) {
            return base.Channel.ServiceRegistrarProductoAsync(producto);
        }
        
        public bool ServiceActualizaProducto(CapaGUI.ServiceEmpleado.Producto producto) {
            return base.Channel.ServiceActualizaProducto(producto);
        }
        
        public System.Threading.Tasks.Task<bool> ServiceActualizaProductoAsync(CapaGUI.ServiceEmpleado.Producto producto) {
            return base.Channel.ServiceActualizaProductoAsync(producto);
        }
        
        public System.Data.DataTable ServiceListaProducto(string filtro, bool sentido) {
            return base.Channel.ServiceListaProducto(filtro, sentido);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ServiceListaProductoAsync(string filtro, bool sentido) {
            return base.Channel.ServiceListaProductoAsync(filtro, sentido);
        }
        
        public System.Data.DataTable ServiceBuscaProducto(string filtro, string valor) {
            return base.Channel.ServiceBuscaProducto(filtro, valor);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ServiceBuscaProductoAsync(string filtro, string valor) {
            return base.Channel.ServiceBuscaProductoAsync(filtro, valor);
        }
        
        public bool ServiceEliminaProducto(string sku) {
            return base.Channel.ServiceEliminaProducto(sku);
        }
        
        public System.Threading.Tasks.Task<bool> ServiceEliminaProductoAsync(string sku) {
            return base.Channel.ServiceEliminaProductoAsync(sku);
        }
        
        public System.Data.DataTable ServiceListaCliente(string filtro, bool sentido) {
            return base.Channel.ServiceListaCliente(filtro, sentido);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ServiceListaClienteAsync(string filtro, bool sentido) {
            return base.Channel.ServiceListaClienteAsync(filtro, sentido);
        }
        
        public System.Data.DataTable ServiceBuscaClienteS(string filtro, string valor) {
            return base.Channel.ServiceBuscaClienteS(filtro, valor);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ServiceBuscaClienteSAsync(string filtro, string valor) {
            return base.Channel.ServiceBuscaClienteSAsync(filtro, valor);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServiceEmpleado.Busca_clientes_utilizando_un_parametro_int1 CapaGUI.ServiceEmpleado.WebServiceUsuarioEmpleadoSoap.ServiceBuscaClienteN(CapaGUI.ServiceEmpleado.Busca_clientes_utilizando_un_parametro_int request) {
            return base.Channel.ServiceBuscaClienteN(request);
        }
        
        public System.Data.DataTable ServiceBuscaClienteN(string filtro, int valor) {
            CapaGUI.ServiceEmpleado.Busca_clientes_utilizando_un_parametro_int inValue = new CapaGUI.ServiceEmpleado.Busca_clientes_utilizando_un_parametro_int();
            inValue.filtro = filtro;
            inValue.valor = valor;
            CapaGUI.ServiceEmpleado.Busca_clientes_utilizando_un_parametro_int1 retVal = ((CapaGUI.ServiceEmpleado.WebServiceUsuarioEmpleadoSoap)(this)).ServiceBuscaClienteN(inValue);
            return retVal.Busca_clientes_utilizando_un_parametro_intResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServiceEmpleado.Busca_clientes_utilizando_un_parametro_int1> CapaGUI.ServiceEmpleado.WebServiceUsuarioEmpleadoSoap.ServiceBuscaClienteNAsync(CapaGUI.ServiceEmpleado.Busca_clientes_utilizando_un_parametro_int request) {
            return base.Channel.ServiceBuscaClienteNAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServiceEmpleado.Busca_clientes_utilizando_un_parametro_int1> ServiceBuscaClienteNAsync(string filtro, int valor) {
            CapaGUI.ServiceEmpleado.Busca_clientes_utilizando_un_parametro_int inValue = new CapaGUI.ServiceEmpleado.Busca_clientes_utilizando_un_parametro_int();
            inValue.filtro = filtro;
            inValue.valor = valor;
            return ((CapaGUI.ServiceEmpleado.WebServiceUsuarioEmpleadoSoap)(this)).ServiceBuscaClienteNAsync(inValue);
        }
        
        public bool ServiceActualizaCliente(CapaGUI.ServiceEmpleado.Cliente cliente) {
            return base.Channel.ServiceActualizaCliente(cliente);
        }
        
        public System.Threading.Tasks.Task<bool> ServiceActualizaClienteAsync(CapaGUI.ServiceEmpleado.Cliente cliente) {
            return base.Channel.ServiceActualizaClienteAsync(cliente);
        }
        
        public bool ServiceEliminaCliente(int id) {
            return base.Channel.ServiceEliminaCliente(id);
        }
        
        public System.Threading.Tasks.Task<bool> ServiceEliminaClienteAsync(int id) {
            return base.Channel.ServiceEliminaClienteAsync(id);
        }
        
        public bool ServiceActualizaUsuario(CapaGUI.ServiceEmpleado.Usuario usuario) {
            return base.Channel.ServiceActualizaUsuario(usuario);
        }
        
        public System.Threading.Tasks.Task<bool> ServiceActualizaUsuarioAsync(CapaGUI.ServiceEmpleado.Usuario usuario) {
            return base.Channel.ServiceActualizaUsuarioAsync(usuario);
        }
        
        public bool ServiceRegistraCliente(CapaGUI.ServiceEmpleado.Cliente cliente) {
            return base.Channel.ServiceRegistraCliente(cliente);
        }
        
        public System.Threading.Tasks.Task<bool> ServiceRegistraClienteAsync(CapaGUI.ServiceEmpleado.Cliente cliente) {
            return base.Channel.ServiceRegistraClienteAsync(cliente);
        }
        
        public System.Data.DataTable ServiceBuscaEmpleado(string filtro, string valor) {
            return base.Channel.ServiceBuscaEmpleado(filtro, valor);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ServiceBuscaEmpleadoAsync(string filtro, string valor) {
            return base.Channel.ServiceBuscaEmpleadoAsync(filtro, valor);
        }
        
        public bool ServiceActualizaEmpleado(CapaGUI.ServiceEmpleado.Empleado empleado) {
            return base.Channel.ServiceActualizaEmpleado(empleado);
        }
        
        public System.Threading.Tasks.Task<bool> ServiceActualizaEmpleadoAsync(CapaGUI.ServiceEmpleado.Empleado empleado) {
            return base.Channel.ServiceActualizaEmpleadoAsync(empleado);
        }
    }
}
