//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaGUIWeb.ServiceReferenceProducto {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceProducto.WebServiceProductoSoap")]
    public interface WebServiceProductoSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceRegistrarProducto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void ServiceRegistrarProducto(CapaGUIWeb.ServiceReferenceProducto.Producto producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceRegistrarProducto", ReplyAction="*")]
        System.Threading.Tasks.Task ServiceRegistrarProductoAsync(CapaGUIWeb.ServiceReferenceProducto.Producto producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceListaProducto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ServiceListaProducto();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceListaProducto", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ServiceListaProductoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceBuscaProductoSku", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaGUIWeb.ServiceReferenceProducto.Producto ServiceBuscaProductoSku(string sku);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceBuscaProductoSku", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaGUIWeb.ServiceReferenceProducto.Producto> ServiceBuscaProductoSkuAsync(string sku);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceBuscaProductoNombre", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaGUIWeb.ServiceReferenceProducto.Producto ServiceBuscaProductoNombre(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceBuscaProductoNombre", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaGUIWeb.ServiceReferenceProducto.Producto> ServiceBuscaProductoNombreAsync(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceActualizaProducto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void ServiceActualizaProducto(CapaGUIWeb.ServiceReferenceProducto.Producto producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceActualizaProducto", ReplyAction="*")]
        System.Threading.Tasks.Task ServiceActualizaProductoAsync(CapaGUIWeb.ServiceReferenceProducto.Producto producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceElmininaProducto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void ServiceElmininaProducto(string sku);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceElmininaProducto", ReplyAction="*")]
        System.Threading.Tasks.Task ServiceElmininaProductoAsync(string sku);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Producto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string skuField;
        
        private string nombreProductoField;
        
        private int valorField;
        
        private string imagenField;
        
        private string unidadMedidaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Sku {
            get {
                return this.skuField;
            }
            set {
                this.skuField = value;
                this.RaisePropertyChanged("Sku");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string NombreProducto {
            get {
                return this.nombreProductoField;
            }
            set {
                this.nombreProductoField = value;
                this.RaisePropertyChanged("NombreProducto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
                this.RaisePropertyChanged("Valor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Imagen {
            get {
                return this.imagenField;
            }
            set {
                this.imagenField = value;
                this.RaisePropertyChanged("Imagen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string UnidadMedida {
            get {
                return this.unidadMedidaField;
            }
            set {
                this.unidadMedidaField = value;
                this.RaisePropertyChanged("UnidadMedida");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceProductoSoapChannel : CapaGUIWeb.ServiceReferenceProducto.WebServiceProductoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceProductoSoapClient : System.ServiceModel.ClientBase<CapaGUIWeb.ServiceReferenceProducto.WebServiceProductoSoap>, CapaGUIWeb.ServiceReferenceProducto.WebServiceProductoSoap {
        
        public WebServiceProductoSoapClient() {
        }
        
        public WebServiceProductoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceProductoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceProductoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceProductoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void ServiceRegistrarProducto(CapaGUIWeb.ServiceReferenceProducto.Producto producto) {
            base.Channel.ServiceRegistrarProducto(producto);
        }
        
        public System.Threading.Tasks.Task ServiceRegistrarProductoAsync(CapaGUIWeb.ServiceReferenceProducto.Producto producto) {
            return base.Channel.ServiceRegistrarProductoAsync(producto);
        }
        
        public System.Data.DataSet ServiceListaProducto() {
            return base.Channel.ServiceListaProducto();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ServiceListaProductoAsync() {
            return base.Channel.ServiceListaProductoAsync();
        }
        
        public CapaGUIWeb.ServiceReferenceProducto.Producto ServiceBuscaProductoSku(string sku) {
            return base.Channel.ServiceBuscaProductoSku(sku);
        }
        
        public System.Threading.Tasks.Task<CapaGUIWeb.ServiceReferenceProducto.Producto> ServiceBuscaProductoSkuAsync(string sku) {
            return base.Channel.ServiceBuscaProductoSkuAsync(sku);
        }
        
        public CapaGUIWeb.ServiceReferenceProducto.Producto ServiceBuscaProductoNombre(string nombre) {
            return base.Channel.ServiceBuscaProductoNombre(nombre);
        }
        
        public System.Threading.Tasks.Task<CapaGUIWeb.ServiceReferenceProducto.Producto> ServiceBuscaProductoNombreAsync(string nombre) {
            return base.Channel.ServiceBuscaProductoNombreAsync(nombre);
        }
        
        public void ServiceActualizaProducto(CapaGUIWeb.ServiceReferenceProducto.Producto producto) {
            base.Channel.ServiceActualizaProducto(producto);
        }
        
        public System.Threading.Tasks.Task ServiceActualizaProductoAsync(CapaGUIWeb.ServiceReferenceProducto.Producto producto) {
            return base.Channel.ServiceActualizaProductoAsync(producto);
        }
        
        public void ServiceElmininaProducto(string sku) {
            base.Channel.ServiceElmininaProducto(sku);
        }
        
        public System.Threading.Tasks.Task ServiceElmininaProductoAsync(string sku) {
            return base.Channel.ServiceElmininaProductoAsync(sku);
        }
    }
}
