//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaGUI.ServiceProducto {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceProducto.WebServiceProductoSoap")]
    public interface WebServiceProductoSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SRegistrarProducto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool SRegistrarProducto(CapaGUI.ServiceProducto.Producto producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SRegistrarProducto", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> SRegistrarProductoAsync(CapaGUI.ServiceProducto.Producto producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SListaProducto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable SListaProducto(string filtro, bool sentido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SListaProducto", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> SListaProductoAsync(string filtro, bool sentido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SBuscaProducto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable SBuscaProducto(string filtro, string valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SBuscaProducto", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> SBuscaProductoAsync(string filtro, string valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SActualizaProducto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool SActualizaProducto(CapaGUI.ServiceProducto.Producto producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SActualizaProducto", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> SActualizaProductoAsync(CapaGUI.ServiceProducto.Producto producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SEliminaProducto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool SEliminaProducto(string sku);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SEliminaProducto", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> SEliminaProductoAsync(string sku);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Producto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string skuField;
        
        private string nombreProductoField;
        
        private int valorField;
        
        private double cantPaqueteField;
        
        private string unidadMedidaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Sku {
            get {
                return this.skuField;
            }
            set {
                this.skuField = value;
                this.RaisePropertyChanged("Sku");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string NombreProducto {
            get {
                return this.nombreProductoField;
            }
            set {
                this.nombreProductoField = value;
                this.RaisePropertyChanged("NombreProducto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
                this.RaisePropertyChanged("Valor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public double CantPaquete {
            get {
                return this.cantPaqueteField;
            }
            set {
                this.cantPaqueteField = value;
                this.RaisePropertyChanged("CantPaquete");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string UnidadMedida {
            get {
                return this.unidadMedidaField;
            }
            set {
                this.unidadMedidaField = value;
                this.RaisePropertyChanged("UnidadMedida");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceProductoSoapChannel : CapaGUI.ServiceProducto.WebServiceProductoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceProductoSoapClient : System.ServiceModel.ClientBase<CapaGUI.ServiceProducto.WebServiceProductoSoap>, CapaGUI.ServiceProducto.WebServiceProductoSoap {
        
        public WebServiceProductoSoapClient() {
        }
        
        public WebServiceProductoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceProductoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceProductoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceProductoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool SRegistrarProducto(CapaGUI.ServiceProducto.Producto producto) {
            return base.Channel.SRegistrarProducto(producto);
        }
        
        public System.Threading.Tasks.Task<bool> SRegistrarProductoAsync(CapaGUI.ServiceProducto.Producto producto) {
            return base.Channel.SRegistrarProductoAsync(producto);
        }
        
        public System.Data.DataTable SListaProducto(string filtro, bool sentido) {
            return base.Channel.SListaProducto(filtro, sentido);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> SListaProductoAsync(string filtro, bool sentido) {
            return base.Channel.SListaProductoAsync(filtro, sentido);
        }
        
        public System.Data.DataTable SBuscaProducto(string filtro, string valor) {
            return base.Channel.SBuscaProducto(filtro, valor);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> SBuscaProductoAsync(string filtro, string valor) {
            return base.Channel.SBuscaProductoAsync(filtro, valor);
        }
        
        public bool SActualizaProducto(CapaGUI.ServiceProducto.Producto producto) {
            return base.Channel.SActualizaProducto(producto);
        }
        
        public System.Threading.Tasks.Task<bool> SActualizaProductoAsync(CapaGUI.ServiceProducto.Producto producto) {
            return base.Channel.SActualizaProductoAsync(producto);
        }
        
        public bool SEliminaProducto(string sku) {
            return base.Channel.SEliminaProducto(sku);
        }
        
        public System.Threading.Tasks.Task<bool> SEliminaProductoAsync(string sku) {
            return base.Channel.SEliminaProductoAsync(sku);
        }
    }
}
