//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaGUI.ServiceReferenceEmpleado {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceEmpleado.WebServiceUsuarioEmpleadoSoap")]
    public interface WebServiceUsuarioEmpleadoSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceRegistrarProducto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ServiceRegistrarProducto(CapaGUI.ServiceReferenceEmpleado.Producto producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceRegistrarProducto", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ServiceRegistrarProductoAsync(CapaGUI.ServiceReferenceEmpleado.Producto producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceActualizaProducto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ServiceActualizaProducto(CapaGUI.ServiceReferenceEmpleado.Producto producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceActualizaProducto", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ServiceActualizaProductoAsync(CapaGUI.ServiceReferenceEmpleado.Producto producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceListaProducto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ServiceListaProducto(string filtro, bool sentido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceListaProducto", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ServiceListaProductoAsync(string filtro, bool sentido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceBuscaProducto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ServiceBuscaProducto(string filtro, string valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceBuscaProducto", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ServiceBuscaProductoAsync(string filtro, string valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceEliminaProducto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ServiceEliminaProducto(string sku);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceEliminaProducto", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ServiceEliminaProductoAsync(string sku);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceListaCliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ServiceListaCliente(string filtro, bool sentido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceListaCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ServiceListaClienteAsync(string filtro, bool sentido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceBuscaCliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ServiceBuscaCliente(string filtro, string valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceBuscaCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ServiceBuscaClienteAsync(string filtro, string valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceActualizaCliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ServiceActualizaCliente(CapaGUI.ServiceReferenceEmpleado.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceActualizaCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ServiceActualizaClienteAsync(CapaGUI.ServiceReferenceEmpleado.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceEliminaCliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ServiceEliminaCliente(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServiceEliminaCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ServiceEliminaClienteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizaUsuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ActualizaUsuario(CapaGUI.ServiceReferenceEmpleado.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizaUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ActualizaUsuarioAsync(CapaGUI.ServiceReferenceEmpleado.Usuario usuario);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Producto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string skuField;
        
        private string nombreProductoField;
        
        private int valorField;
        
        private double cantPaqueteField;
        
        private string unidadMedidaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Sku {
            get {
                return this.skuField;
            }
            set {
                this.skuField = value;
                this.RaisePropertyChanged("Sku");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string NombreProducto {
            get {
                return this.nombreProductoField;
            }
            set {
                this.nombreProductoField = value;
                this.RaisePropertyChanged("NombreProducto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
                this.RaisePropertyChanged("Valor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public double CantPaquete {
            get {
                return this.cantPaqueteField;
            }
            set {
                this.cantPaqueteField = value;
                this.RaisePropertyChanged("CantPaquete");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string UnidadMedida {
            get {
                return this.unidadMedidaField;
            }
            set {
                this.unidadMedidaField = value;
                this.RaisePropertyChanged("UnidadMedida");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Usuario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idUsuarioField;
        
        private string nombreUsuarioField;
        
        private string contrasenaField;
        
        private string rolField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int IdUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
                this.RaisePropertyChanged("IdUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string NombreUsuario {
            get {
                return this.nombreUsuarioField;
            }
            set {
                this.nombreUsuarioField = value;
                this.RaisePropertyChanged("NombreUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Contrasena {
            get {
                return this.contrasenaField;
            }
            set {
                this.contrasenaField = value;
                this.RaisePropertyChanged("Contrasena");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Rol {
            get {
                return this.rolField;
            }
            set {
                this.rolField = value;
                this.RaisePropertyChanged("Rol");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Cliente : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int tbUsuario_IdUsuarioField;
        
        private string nombreCompletoField;
        
        private int edadField;
        
        private int telefonoField;
        
        private string emailField;
        
        private string sexoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int TbUsuario_IdUsuario {
            get {
                return this.tbUsuario_IdUsuarioField;
            }
            set {
                this.tbUsuario_IdUsuarioField = value;
                this.RaisePropertyChanged("TbUsuario_IdUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string NombreCompleto {
            get {
                return this.nombreCompletoField;
            }
            set {
                this.nombreCompletoField = value;
                this.RaisePropertyChanged("NombreCompleto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Edad {
            get {
                return this.edadField;
            }
            set {
                this.edadField = value;
                this.RaisePropertyChanged("Edad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("Telefono");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
                this.RaisePropertyChanged("Sexo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceUsuarioEmpleadoSoapChannel : CapaGUI.ServiceReferenceEmpleado.WebServiceUsuarioEmpleadoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceUsuarioEmpleadoSoapClient : System.ServiceModel.ClientBase<CapaGUI.ServiceReferenceEmpleado.WebServiceUsuarioEmpleadoSoap>, CapaGUI.ServiceReferenceEmpleado.WebServiceUsuarioEmpleadoSoap {
        
        public WebServiceUsuarioEmpleadoSoapClient() {
        }
        
        public WebServiceUsuarioEmpleadoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceUsuarioEmpleadoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceUsuarioEmpleadoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceUsuarioEmpleadoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool ServiceRegistrarProducto(CapaGUI.ServiceReferenceEmpleado.Producto producto) {
            return base.Channel.ServiceRegistrarProducto(producto);
        }
        
        public System.Threading.Tasks.Task<bool> ServiceRegistrarProductoAsync(CapaGUI.ServiceReferenceEmpleado.Producto producto) {
            return base.Channel.ServiceRegistrarProductoAsync(producto);
        }
        
        public bool ServiceActualizaProducto(CapaGUI.ServiceReferenceEmpleado.Producto producto) {
            return base.Channel.ServiceActualizaProducto(producto);
        }
        
        public System.Threading.Tasks.Task<bool> ServiceActualizaProductoAsync(CapaGUI.ServiceReferenceEmpleado.Producto producto) {
            return base.Channel.ServiceActualizaProductoAsync(producto);
        }
        
        public System.Data.DataTable ServiceListaProducto(string filtro, bool sentido) {
            return base.Channel.ServiceListaProducto(filtro, sentido);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ServiceListaProductoAsync(string filtro, bool sentido) {
            return base.Channel.ServiceListaProductoAsync(filtro, sentido);
        }
        
        public System.Data.DataTable ServiceBuscaProducto(string filtro, string valor) {
            return base.Channel.ServiceBuscaProducto(filtro, valor);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ServiceBuscaProductoAsync(string filtro, string valor) {
            return base.Channel.ServiceBuscaProductoAsync(filtro, valor);
        }
        
        public bool ServiceEliminaProducto(string sku) {
            return base.Channel.ServiceEliminaProducto(sku);
        }
        
        public System.Threading.Tasks.Task<bool> ServiceEliminaProductoAsync(string sku) {
            return base.Channel.ServiceEliminaProductoAsync(sku);
        }
        
        public System.Data.DataTable ServiceListaCliente(string filtro, bool sentido) {
            return base.Channel.ServiceListaCliente(filtro, sentido);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ServiceListaClienteAsync(string filtro, bool sentido) {
            return base.Channel.ServiceListaClienteAsync(filtro, sentido);
        }
        
        public System.Data.DataTable ServiceBuscaCliente(string filtro, string valor) {
            return base.Channel.ServiceBuscaCliente(filtro, valor);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ServiceBuscaClienteAsync(string filtro, string valor) {
            return base.Channel.ServiceBuscaClienteAsync(filtro, valor);
        }
        
        public bool ServiceActualizaCliente(CapaGUI.ServiceReferenceEmpleado.Cliente cliente) {
            return base.Channel.ServiceActualizaCliente(cliente);
        }
        
        public System.Threading.Tasks.Task<bool> ServiceActualizaClienteAsync(CapaGUI.ServiceReferenceEmpleado.Cliente cliente) {
            return base.Channel.ServiceActualizaClienteAsync(cliente);
        }
        
        public bool ServiceEliminaCliente(int id) {
            return base.Channel.ServiceEliminaCliente(id);
        }
        
        public System.Threading.Tasks.Task<bool> ServiceEliminaClienteAsync(int id) {
            return base.Channel.ServiceEliminaClienteAsync(id);
        }
        
        public bool ActualizaUsuario(CapaGUI.ServiceReferenceEmpleado.Usuario usuario) {
            return base.Channel.ActualizaUsuario(usuario);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizaUsuarioAsync(CapaGUI.ServiceReferenceEmpleado.Usuario usuario) {
            return base.Channel.ActualizaUsuarioAsync(usuario);
        }
    }
}
